.TH "PMFIND" "1" "2026-02-27" "0.1" "pmfind Manual"
.SH NAME
pmfind \- Search PubMed for given TERM(s) and return...
.SH SYNOPSIS
.B pmfind
[OPTIONS] TERM
.SH DESCRIPTION
Search PubMed for given TERM(s) and return a list of URLs and titles
from the first page of search results.
.SH OPTIONS
.TP
\fB\-\-version\fP
Show the version and exit.
